CREATE DATABASE IF NOT EXISTS jaam;

USE jaam;

CREATE TABLE IF NOT EXISTS clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chip_id VARCHAR(32),
    firmware VARCHAR(32),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    connected BOOL DEFAULT TRUE,
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS connections (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chip_id VARCHAR(32),
    firmware VARCHAR(32),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    connected BOOL DEFAULT TRUE
);